runtime: nodejs16
service: event-matcher-api

env_variables:
  NODE_ENV: 'production'
  POSTGRES_HOST: free-tier14.aws-us-east-1.cockroachlabs.cloud
  POSTGRES_PORT: 26257
  POSTGRES_USER: cepedaio
  POSTGRES_PASSWORD: JReLSVmYrNub00DRQsIlEg
  POSTGRES_CERT: certs/postgres.crt
